[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "tv-generator"
version = "0.8.9"
dependencies = [
    "click",
    "requests",
    "pandas",
    "PyYAML",
    "openapi-spec-validator",
    "toml",
    "requests_cache",
]

[project.scripts]
tvgen = "src.cli:cli"

[tool.setuptools]
packages = ["src", "src.api", "src.generator", "src.utils"]

[tool.setuptools.package-dir]
src = "src"

[tool.mypy]
ignore_missing_imports = true
ignore_errors = true
