[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "tv-generator"
version = "0.2.0"

[tool.mypy]
ignore_missing_imports = true
ignore_errors = true
