openapi: 3.1.0
x-oai-custom-action-schema-version: v1
info:
  title: Unofficial TradingView Bond API
  version: 1.0.36
servers:
  - url: https://scanner.tradingview.com
paths:
  /bond/scan:
    post:
      summary: Scan bond market data
      description: 'Send a BondScanRequest payload and receive a BondScanResponse.
        The response contains fields defined in #/components/schemas/BondFields.'
      operationId: BondScan
      x-openai-isConsequential: false
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BondScanRequest'
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BondScanResponse'
        '400':
          description: Bad Request
        '500':
          description: Server Error
  /bond/search:
    post:
      summary: Search bond market data
      description: 'Send a BondSearchRequest payload and receive a BondSearchResponse.
        The response contains fields defined in #/components/schemas/BondFields.'
      operationId: BondSearch
      x-openai-isConsequential: false
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BondSearchRequest'
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BondSearchResponse'
        '400':
          description: Bad Request
        '500':
          description: Server Error
  /bond/history:
    post:
      summary: History bond market data
      description: 'Send a BondHistoryRequest payload and receive a BondHistoryResponse.
        The response contains fields defined in #/components/schemas/BondFields.'
      operationId: BondHistory
      x-openai-isConsequential: false
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BondHistoryRequest'
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BondHistoryResponse'
        '400':
          description: Bad Request
        '500':
          description: Server Error
  /bond/summary:
    post:
      summary: Summary bond market data
      description: 'Send a BondSummaryRequest payload and receive a BondSummaryResponse.
        The response contains fields defined in #/components/schemas/BondFields.'
      operationId: BondSummary
      x-openai-isConsequential: false
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BondSummaryRequest'
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BondSummaryResponse'
        '400':
          description: Bad Request
        '500':
          description: Server Error
  /bond/metainfo:
    post:
      summary: Get bond metainfo
      description: Returns the list of available fields for bond.
      operationId: BondMetainfo
      x-openai-isConsequential: false
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BondMetainfoResponse'
        '400':
          description: Bad Request
        '500':
          description: Server Error
components:
  schemas:
    Num:
      type: number
    Str:
      type: string
    Bool:
      type: boolean
    Time:
      type: string
      format: date-time
    Array:
      type: array
      items: {}
    NumericFieldNoTimeframe:
      type: string
      enum:
        - close
    NumericFieldWithTimeframe:
      type: string
      pattern: ^[A-Z0-9_+\[\]]+\|(1|5|15|30|60|120|240|1D|1W)$
    BondFields:
      type: object
      properties:
        close:
          $ref: '#/components/schemas/Num'
          description: Close
    BondScanRequest:
      type: object
      properties:
        symbols:
          type: object
          properties:
            tickers:
              type: array
              items:
                type: string
            query:
              type: object
              properties:
                types:
                  type: array
                  items:
                    type: string
        columns:
          type: array
          items:
            type: string
        filter:
          type: object
        filter2:
          type: object
        sort:
          type: object
        range:
          type: object
      required:
        - symbols
        - columns
    BondScanResponse:
      type: object
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/BondFields'
    BondSearchRequest:
      type: object
    BondHistoryRequest:
      type: object
    BondSummaryRequest:
      type: object
    BondSearchResponse:
      type: object
    BondHistoryResponse:
      type: object
    BondSummaryResponse:
      type: object
    BondMetainfoResponse:
      type: object
      properties:
        fields:
          type: array
          items:
            type: string
