openapi: 3.1.0
x-oai-custom-action-schema-version: v1
info:
  title: Unofficial TradingView Cfd API
  version: 1.0.35
servers:
  - url: https://scanner.tradingview.com
paths:
  /cfd/scan:
    post:
      summary: Scan cfd market data
      description: 'Send a CfdScanRequest payload and receive a CfdScanResponse. The
        response contains fields defined in #/components/schemas/CfdFields.'
      operationId: CfdScan
      x-openai-isConsequential: false
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CfdScanRequest'
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CfdScanResponse'
        '400':
          description: Bad Request
        '500':
          description: Server Error
  /cfd/search:
    post:
      summary: Search cfd market data
      description: 'Send a CfdSearchRequest payload and receive a CfdSearchResponse.
        The response contains fields defined in #/components/schemas/CfdFields.'
      operationId: CfdSearch
      x-openai-isConsequential: false
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CfdSearchRequest'
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CfdSearchResponse'
        '400':
          description: Bad Request
        '500':
          description: Server Error
  /cfd/history:
    post:
      summary: History cfd market data
      description: 'Send a CfdHistoryRequest payload and receive a CfdHistoryResponse.
        The response contains fields defined in #/components/schemas/CfdFields.'
      operationId: CfdHistory
      x-openai-isConsequential: false
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CfdHistoryRequest'
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CfdHistoryResponse'
        '400':
          description: Bad Request
        '500':
          description: Server Error
  /cfd/summary:
    post:
      summary: Summary cfd market data
      description: 'Send a CfdSummaryRequest payload and receive a CfdSummaryResponse.
        The response contains fields defined in #/components/schemas/CfdFields.'
      operationId: CfdSummary
      x-openai-isConsequential: false
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CfdSummaryRequest'
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CfdSummaryResponse'
        '400':
          description: Bad Request
        '500':
          description: Server Error
  /cfd/metainfo:
    post:
      summary: Get cfd metainfo
      description: Returns the list of available fields for cfd.
      operationId: CfdMetainfo
      x-openai-isConsequential: false
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CfdMetainfoResponse'
        '400':
          description: Bad Request
        '500':
          description: Server Error
components:
  schemas:
    Num:
      type: number
    Str:
      type: string
    Bool:
      type: boolean
    Time:
      type: string
      format: date-time
    Array:
      type: array
      items: {}
    NumericFieldNoTimeframe:
      type: string
      enum:
        - close
    NumericFieldWithTimeframe:
      type: string
      pattern: ^[A-Z0-9_+\[\]]+\|(1|5|15|30|60|120|240|1D|1W)$
    CfdFields:
      type: object
      properties:
        close:
          $ref: '#/components/schemas/Num'
          description: Close
    CfdScanRequest:
      type: object
      properties:
        symbols:
          type: object
          properties:
            tickers:
              type: array
              items:
                type: string
            query:
              type: object
              properties:
                types:
                  type: array
                  items:
                    type: string
        columns:
          type: array
          items:
            type: string
        filter:
          type: object
        filter2:
          type: object
        sort:
          type: object
        range:
          type: object
      required:
        - symbols
        - columns
    CfdScanResponse:
      type: object
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/CfdFields'
    CfdSearchRequest:
      type: object
    CfdHistoryRequest:
      type: object
    CfdSummaryRequest:
      type: object
    CfdSearchResponse:
      type: object
    CfdHistoryResponse:
      type: object
    CfdSummaryResponse:
      type: object
    CfdMetainfoResponse:
      type: object
      properties:
        fields:
          type: array
          items:
            type: string
