openapi: 3.1.0
x-oai-custom-action-schema-version: v1
info:
  title: Unofficial TradingView Coin API
  version: 1.0.42
servers:
- url: https://scanner.tradingview.com
paths:
  /coin/scan:
    post:
      summary: Scan coin market data
      description: 'Send a CoinScanRequest payload and receive a CoinScanResponse.
        The response contains fields defined in #/components/schemas/CoinFields.'
      operationId: CoinScan
      x-openai-isConsequential: false
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CoinScanRequest'
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CoinScanResponse'
        '400':
          description: Bad Request
        '500':
          description: Server Error
  /coin/search:
    post:
      summary: Search coin market data
      description: 'Send a CoinSearchRequest payload and receive a CoinSearchResponse.
        The response contains fields defined in #/components/schemas/CoinFields.'
      operationId: CoinSearch
      x-openai-isConsequential: false
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CoinSearchRequest'
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CoinSearchResponse'
        '400':
          description: Bad Request
        '500':
          description: Server Error
  /coin/history:
    post:
      summary: History coin market data
      description: 'Send a CoinHistoryRequest payload and receive a CoinHistoryResponse.
        The response contains fields defined in #/components/schemas/CoinFields.'
      operationId: CoinHistory
      x-openai-isConsequential: false
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CoinHistoryRequest'
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CoinHistoryResponse'
        '400':
          description: Bad Request
        '500':
          description: Server Error
  /coin/summary:
    post:
      summary: Summary coin market data
      description: 'Send a CoinSummaryRequest payload and receive a CoinSummaryResponse.
        The response contains fields defined in #/components/schemas/CoinFields.'
      operationId: CoinSummary
      x-openai-isConsequential: false
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CoinSummaryRequest'
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CoinSummaryResponse'
        '400':
          description: Bad Request
        '500':
          description: Server Error
  /coin/numeric:
    get:
      summary: Get numeric field for coin
      operationId: CoinNumeric
      x-openai-isConsequential: false
      parameters:
      - name: symbol
        in: query
        required: true
        schema:
          type: string
      - name: field
        in: query
        required: true
        schema:
          oneOf:
          - $ref: '#/components/schemas/NumericFieldWithTimeframe'
          - $ref: '#/components/schemas/NumericFieldNoTimeframe'
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Num'
        '400':
          description: Bad Request
        '500':
          description: Server Error
  /coin/metainfo:
    post:
      summary: Get coin metainfo
      description: Returns the list of available fields for coin.
      operationId: CoinMetainfo
      x-openai-isConsequential: false
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CoinMetainfoResponse'
        '400':
          description: Bad Request
        '500':
          description: Server Error
components:
  schemas:
    Num:
      type: number
    Str:
      type: string
    Bool:
      type: boolean
    Time:
      type: string
      format: date-time
    Array:
      type: array
      items: {}
    NumericFieldNoTimeframe:
      type: string
      enum:
      - close
    NumericFieldWithTimeframe:
      type: string
      enum: []
      pattern: ^[A-Za-z0-9_.\[\]]+\|(1|5|15|30|60|120|240|1D|1W)$
    CoinFields:
      type: object
      properties:
        close:
          $ref: '#/components/schemas/Num'
          description: Close
    CoinScanRequest:
      type: object
      properties:
        symbols:
          type: object
          properties:
            tickers:
              type: array
              items:
                type: string
            query:
              type: object
              properties:
                types:
                  type: array
                  items:
                    type: string
        columns:
          type: array
          items:
            type: string
        filter:
          type: object
        filter2:
          type: object
        sort:
          type: object
        range:
          type: object
      required:
      - symbols
      - columns
    CoinScanResponse:
      type: object
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/CoinFields'
    CoinSearchRequest:
      type: object
    CoinHistoryRequest:
      type: object
    CoinSummaryRequest:
      type: object
    CoinSearchResponse:
      type: object
    CoinHistoryResponse:
      type: object
    CoinSummaryResponse:
      type: object
    CoinMetainfoResponse:
      type: object
      properties:
        fields:
          type: array
          items:
            type: string
