openapi: 3.1.0
x-oai-custom-action-schema-version: v1
info:
  title: Unofficial TradingView Crypto API
  version: 1.0.22
servers:
  - url: https://scanner.tradingview.com
paths:
  /crypto/scan:
    post:
      summary: Scan crypto market data
      description: 'Send a CryptoScanRequest payload and receive a CryptoScanResponse.
        The response contains fields defined in #/components/schemas/CryptoFields.'
      operationId: CryptoScan
      x-openai-isConsequential: false
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CryptoScanRequest'
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CryptoScanResponse'
        '400':
          description: Bad Request
        '500':
          description: Server Error
  /crypto/search:
    post:
      summary: Search crypto market data
      description: 'Send a CryptoSearchRequest payload and receive a CryptoSearchResponse.
        The response contains fields defined in #/components/schemas/CryptoFields.'
      operationId: CryptoSearch
      x-openai-isConsequential: false
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CryptoSearchRequest'
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CryptoSearchResponse'
        '400':
          description: Bad Request
        '500':
          description: Server Error
  /crypto/history:
    post:
      summary: History crypto market data
      description: 'Send a CryptoHistoryRequest payload and receive a CryptoHistoryResponse.
        The response contains fields defined in #/components/schemas/CryptoFields.'
      operationId: CryptoHistory
      x-openai-isConsequential: false
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CryptoHistoryRequest'
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CryptoHistoryResponse'
        '400':
          description: Bad Request
        '500':
          description: Server Error
  /crypto/summary:
    post:
      summary: Summary crypto market data
      description: 'Send a CryptoSummaryRequest payload and receive a CryptoSummaryResponse.
        The response contains fields defined in #/components/schemas/CryptoFields.'
      operationId: CryptoSummary
      x-openai-isConsequential: false
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CryptoSummaryRequest'
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CryptoSummaryResponse'
        '400':
          description: Bad Request
        '500':
          description: Server Error
  /crypto/metainfo:
    post:
      summary: Get crypto metainfo
      description: Returns the list of available fields for crypto.
      operationId: CryptoMetainfo
      x-openai-isConsequential: false
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CryptoMetainfoResponse'
        '400':
          description: Bad Request
        '500':
          description: Server Error
components:
  schemas:
    Num:
      type: number
    Str:
      type: string
    Bool:
      type: boolean
    Time:
      type: string
      format: date-time
    Array:
      type: array
      items: {}
    NumericFieldNoTimeframe:
      type: string
      enum: []
    NumericFieldWithTimeframe:
      type: string
      pattern: ^[A-Z0-9_+\[\]]+\|(1|5|15|30|60|120|240|1D|1W)$
    CryptoFields:
      type: object
      properties:
        close:
          $ref: '#/components/schemas/Num'
          description: Close
        open:
          $ref: '#/components/schemas/Str'
          description: Open
    CryptoScanRequest:
      type: object
      properties:
        symbols:
          type: object
          properties:
            tickers:
              type: array
              items:
                type: string
            query:
              type: object
              properties:
                types:
                  type: array
                  items:
                    type: string
        columns:
          type: array
          items:
            type: string
        filter:
          type: object
        filter2:
          type: object
        sort:
          type: object
        range:
          type: object
      required:
        - symbols
        - columns
    CryptoScanResponse:
      type: object
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/CryptoFields'
    CryptoSearchRequest:
      type: object
    CryptoHistoryRequest:
      type: object
    CryptoSummaryRequest:
      type: object
    CryptoSearchResponse:
      type: object
    CryptoHistoryResponse:
      type: object
    CryptoSummaryResponse:
      type: object
    CryptoMetainfoResponse:
      type: object
      properties:
        fields:
          type: array
          items:
            type: string
