openapi: 3.1.0
x-oai-custom-action-schema-version: v1
info:
  title: Unofficial TradingView Forex API
  version: 1.0.48
servers:
  - url: https://scanner.tradingview.com
paths:
  /forex/scan:
    post:
      summary: Scan forex market data
      description: 'Send a ForexScanRequest payload and receive a ForexScanResponse.
        The response contains fields defined in #/components/schemas/ForexFields.'
      operationId: ForexScan
      x-openai-isConsequential: false
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ForexScanRequest'
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ForexScanResponse'
        '400':
          description: Bad Request
        '500':
          description: Server Error
  /forex/search:
    post:
      summary: Search forex market data
      description: 'Send a ForexSearchRequest payload and receive a ForexSearchResponse.
        The response contains fields defined in #/components/schemas/ForexFields.'
      operationId: ForexSearch
      x-openai-isConsequential: false
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ForexSearchRequest'
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ForexSearchResponse'
        '400':
          description: Bad Request
        '500':
          description: Server Error
  /forex/history:
    post:
      summary: History forex market data
      description: 'Send a ForexHistoryRequest payload and receive a ForexHistoryResponse.
        The response contains fields defined in #/components/schemas/ForexFields.'
      operationId: ForexHistory
      x-openai-isConsequential: false
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ForexHistoryRequest'
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ForexHistoryResponse'
        '400':
          description: Bad Request
        '500':
          description: Server Error
  /forex/summary:
    post:
      summary: Summary forex market data
      description: 'Send a ForexSummaryRequest payload and receive a ForexSummaryResponse.
        The response contains fields defined in #/components/schemas/ForexFields.'
      operationId: ForexSummary
      x-openai-isConsequential: false
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ForexSummaryRequest'
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ForexSummaryResponse'
        '400':
          description: Bad Request
        '500':
          description: Server Error
  /forex/numeric:
    get:
      summary: Get numeric field for forex
      operationId: ForexNumeric
      x-openai-isConsequential: false
      parameters:
        - name: symbol
          in: query
          required: true
          schema:
            type: string
        - name: field
          in: query
          required: true
          schema:
            oneOf:
              - $ref: '#/components/schemas/NumericFieldWithTimeframe'
              - $ref: '#/components/schemas/NumericFieldNoTimeframe'
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Num'
        '400':
          description: Bad Request
        '500':
          description: Server Error
  /forex/metainfo:
    post:
      summary: Get forex metainfo
      description: Returns the list of available fields for forex.
      operationId: ForexMetainfo
      x-openai-isConsequential: false
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ForexMetainfoResponse'
        '400':
          description: Bad Request
        '500':
          description: Server Error
components:
  schemas:
    Num:
      type: number
    Str:
      type: string
    Bool:
      type: boolean
    Time:
      type: string
      format: date-time
    Array:
      type: array
      items: {}
    NumericFieldNoTimeframe:
      type: string
      enum:
        - close
    NumericFieldWithTimeframe:
      type: string
      enum: []
      pattern: ^[A-Za-z0-9_.\[\]]+\|(1|5|15|30|60|120|240|1D|1W)$
    ForexFields:
      type: object
      properties:
        close:
          $ref: '#/components/schemas/Num'
          description: Close
    ForexScanRequest:
      type: object
      properties:
        symbols:
          type: object
          properties:
            tickers:
              type: array
              items:
                type: string
            query:
              type: object
              properties:
                types:
                  type: array
                  items:
                    type: string
        columns:
          type: array
          items:
            type: string
        filter:
          type: object
        filter2:
          type: object
        sort:
          type: object
        range:
          type: object
      required:
        - symbols
        - columns
    ForexScanResponse:
      type: object
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/ForexFields'
    ForexSearchRequest:
      type: object
    ForexHistoryRequest:
      type: object
    ForexSummaryRequest:
      type: object
    ForexSearchResponse:
      type: object
    ForexHistoryResponse:
      type: object
    ForexSummaryResponse:
      type: object
    ForexMetainfoResponse:
      type: object
      properties:
        fields:
          type: array
          items:
            type: string
