openapi: 3.1.0
x-oai-custom-action-schema-version: v1
info:
  title: Unofficial TradingView Futures API
  version: 1.0.35
servers:
  - url: https://scanner.tradingview.com
paths:
  /futures/scan:
    post:
      summary: Scan futures market data
      description: 'Send a FuturesScanRequest payload and receive a FuturesScanResponse.
        The response contains fields defined in #/components/schemas/FuturesFields.'
      operationId: FuturesScan
      x-openai-isConsequential: false
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FuturesScanRequest'
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FuturesScanResponse'
        '400':
          description: Bad Request
        '500':
          description: Server Error
  /futures/search:
    post:
      summary: Search futures market data
      description: 'Send a FuturesSearchRequest payload and receive a FuturesSearchResponse.
        The response contains fields defined in #/components/schemas/FuturesFields.'
      operationId: FuturesSearch
      x-openai-isConsequential: false
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FuturesSearchRequest'
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FuturesSearchResponse'
        '400':
          description: Bad Request
        '500':
          description: Server Error
  /futures/history:
    post:
      summary: History futures market data
      description: 'Send a FuturesHistoryRequest payload and receive a FuturesHistoryResponse.
        The response contains fields defined in #/components/schemas/FuturesFields.'
      operationId: FuturesHistory
      x-openai-isConsequential: false
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FuturesHistoryRequest'
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FuturesHistoryResponse'
        '400':
          description: Bad Request
        '500':
          description: Server Error
  /futures/summary:
    post:
      summary: Summary futures market data
      description: 'Send a FuturesSummaryRequest payload and receive a FuturesSummaryResponse.
        The response contains fields defined in #/components/schemas/FuturesFields.'
      operationId: FuturesSummary
      x-openai-isConsequential: false
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FuturesSummaryRequest'
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FuturesSummaryResponse'
        '400':
          description: Bad Request
        '500':
          description: Server Error
  /futures/metainfo:
    post:
      summary: Get futures metainfo
      description: Returns the list of available fields for futures.
      operationId: FuturesMetainfo
      x-openai-isConsequential: false
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FuturesMetainfoResponse'
        '400':
          description: Bad Request
        '500':
          description: Server Error
components:
  schemas:
    Num:
      type: number
    Str:
      type: string
    Bool:
      type: boolean
    Time:
      type: string
      format: date-time
    Array:
      type: array
      items: {}
    NumericFieldNoTimeframe:
      type: string
      enum:
        - close
    NumericFieldWithTimeframe:
      type: string
      pattern: ^[A-Z0-9_+\[\]]+\|(1|5|15|30|60|120|240|1D|1W)$
    FuturesFields:
      type: object
      properties:
        close:
          $ref: '#/components/schemas/Num'
          description: Close
    FuturesScanRequest:
      type: object
      properties:
        symbols:
          type: object
          properties:
            tickers:
              type: array
              items:
                type: string
            query:
              type: object
              properties:
                types:
                  type: array
                  items:
                    type: string
        columns:
          type: array
          items:
            type: string
        filter:
          type: object
        filter2:
          type: object
        sort:
          type: object
        range:
          type: object
      required:
        - symbols
        - columns
    FuturesScanResponse:
      type: object
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/FuturesFields'
    FuturesSearchRequest:
      type: object
    FuturesHistoryRequest:
      type: object
    FuturesSummaryRequest:
      type: object
    FuturesSearchResponse:
      type: object
    FuturesHistoryResponse:
      type: object
    FuturesSummaryResponse:
      type: object
    FuturesMetainfoResponse:
      type: object
      properties:
        fields:
          type: array
          items:
            type: string
