openapi: 3.1.0
x-oai-custom-action-schema-version: v1
info:
  title: Unofficial TradingView Stocks API
  version: 1.0.35
servers:
  - url: https://scanner.tradingview.com
paths:
  /stocks/scan:
    post:
      summary: Scan stocks market data
      description: 'Send a StocksScanRequest payload and receive a StocksScanResponse.
        The response contains fields defined in #/components/schemas/StocksFields.'
      operationId: StocksScan
      x-openai-isConsequential: false
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/StocksScanRequest'
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StocksScanResponse'
        '400':
          description: Bad Request
        '500':
          description: Server Error
  /stocks/search:
    post:
      summary: Search stocks market data
      description: 'Send a StocksSearchRequest payload and receive a StocksSearchResponse.
        The response contains fields defined in #/components/schemas/StocksFields.'
      operationId: StocksSearch
      x-openai-isConsequential: false
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/StocksSearchRequest'
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StocksSearchResponse'
        '400':
          description: Bad Request
        '500':
          description: Server Error
  /stocks/history:
    post:
      summary: History stocks market data
      description: 'Send a StocksHistoryRequest payload and receive a StocksHistoryResponse.
        The response contains fields defined in #/components/schemas/StocksFields.'
      operationId: StocksHistory
      x-openai-isConsequential: false
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/StocksHistoryRequest'
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StocksHistoryResponse'
        '400':
          description: Bad Request
        '500':
          description: Server Error
  /stocks/summary:
    post:
      summary: Summary stocks market data
      description: 'Send a StocksSummaryRequest payload and receive a StocksSummaryResponse.
        The response contains fields defined in #/components/schemas/StocksFields.'
      operationId: StocksSummary
      x-openai-isConsequential: false
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/StocksSummaryRequest'
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StocksSummaryResponse'
        '400':
          description: Bad Request
        '500':
          description: Server Error
  /stocks/metainfo:
    post:
      summary: Get stocks metainfo
      description: Returns the list of available fields for stocks.
      operationId: StocksMetainfo
      x-openai-isConsequential: false
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StocksMetainfoResponse'
        '400':
          description: Bad Request
        '500':
          description: Server Error
components:
  schemas:
    Num:
      type: number
    Str:
      type: string
    Bool:
      type: boolean
    Time:
      type: string
      format: date-time
    Array:
      type: array
      items: {}
    NumericFieldNoTimeframe:
      type: string
      enum:
        - close
    NumericFieldWithTimeframe:
      type: string
      pattern: ^[A-Z0-9_+\[\]]+\|(1|5|15|30|60|120|240|1D|1W)$
    StocksFields:
      type: object
      properties:
        close:
          $ref: '#/components/schemas/Num'
          description: Close
    StocksScanRequest:
      type: object
      properties:
        symbols:
          type: object
          properties:
            tickers:
              type: array
              items:
                type: string
            query:
              type: object
              properties:
                types:
                  type: array
                  items:
                    type: string
        columns:
          type: array
          items:
            type: string
        filter:
          type: object
        filter2:
          type: object
        sort:
          type: object
        range:
          type: object
      required:
        - symbols
        - columns
    StocksScanResponse:
      type: object
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/StocksFields'
    StocksSearchRequest:
      type: object
    StocksHistoryRequest:
      type: object
    StocksSummaryRequest:
      type: object
    StocksSearchResponse:
      type: object
    StocksHistoryResponse:
      type: object
    StocksSummaryResponse:
      type: object
    StocksMetainfoResponse:
      type: object
      properties:
        fields:
          type: array
          items:
            type: string
