name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 3 * * 1'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12']
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black flake8 mypy pytest openapi-spec-validator requests_mock \
            types-requests types-PyYAML types-toml -r requirements.txt
          pip install -e .
      - name: Format
        run: black --check .
      - name: Lint
        run: flake8 .
      - name: Type check
        run: mypy --strict src/
      - name: Test
        run: pytest -q
      - name: Generate spec
        run: tvgen generate --market crypto --output specs/openapi_crypto.yaml
      - name: Validate OpenAPI
        run: openapi-spec-validator specs/openapi_crypto.yaml
