---
# yamllint disable rule:truthy rule:line-length
name: daily-specs
# Network access to scanner.tradingview.com is required for tvgen build

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
      - name: Cache Poetry dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pypoetry
          key: ${{ runner.os }}-poetry-${{ hashFiles('poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-poetry-
      - name: Install tools
        run: |
          python -m pip install --upgrade pip
          pip install poetry openapi-spec-validator
      - name: Install dependencies
        run: |
          poetry install --no-interaction --no-root
      - name: Debug tvgen installation
        # Verify tvgen CLI can run before invoking it in subsequent steps
        run: |
          poetry run tvgen --help || echo "tvgen is not installed or not in PATH"
      - name: Build specs
        # Retry to handle temporary network issues when contacting TradingView
        run: |
          for i in {1..3}; do
            poetry run tvgen build --indir results --outdir specs && break
            sleep 10
          done
      - name: Validate generated specs
        run: |
          for spec in specs/*.yaml; do
            openapi-spec-validator "$spec"
          done
      - name: Check size limit
        run: |
          for spec in specs/*.yaml; do
            python -c "import os,sys; s=os.path.getsize('$spec'); assert s<1048576, 'Spec size exceeds 1MB!'"
          done
      - name: Commit and create PR if spec changed
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"
          if git diff --quiet HEAD -- specs/*.yaml; then
            echo "No changes detected"
            exit 0
          fi
          branch="specs-${{ github.run_number }}"
          git checkout -b "$branch"
          git add results/** specs/*.yaml
          git commit -m 'chore: update specs'
          git push origin "$branch"
          python - <<'PY'
          from codex_actions import create_pull_request

          create_pull_request(
              title="Update OpenAPI specs",
              body="Спецификация обновлена автоматически на основе новых данных с TradingView /metainfo",
          )
          PY
      - name: Finish
        run: exit 0
