---
# yamllint disable rule:truthy rule:line-length
name: daily-specs

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
      - name: Install tools
        run: |
          python -m pip install --upgrade pip
          pip install poetry openapi-spec-validator
      - name: Install dependencies
        run: |
          poetry install --no-interaction --no-root
      - name: Collect full data
        run: poetry run tvgen collect-full --scope coin
      - name: Generate spec
        run: poetry run tvgen generate --scope coin
      - name: Validate generated spec
        run: openapi-spec-validator specs/coin.yaml
      - name: Check size limit
        run: python -c "import os,sys; s=os.path.getsize('specs/coin.yaml'); assert s<1048576"
      - name: Commit and create PR if spec changed
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"
          if git diff --quiet HEAD -- specs/coin.yaml; then
            echo "No changes detected"
            exit 0
          fi
          branch="coin-spec-${{ github.run_number }}"
          git checkout -b "$branch"
          git add results/** specs/coin.yaml
          git commit -m 'chore: update coin spec'
          git push origin "$branch"
          gh pr create --title 'Update coin spec' --body 'Спецификация обновлена автоматически на основе новых данных с TradingView /metainfo'
      - name: Finish
        run: exit 0
