---
name: Update Specs
# yamllint disable rule:truthy rule:line-length

on:
  workflow_dispatch: {}  # yamllint disable-line rule:truthy
  schedule:
    - cron: '0 2 * * *'

jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12']
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Actionlint
        uses: rhysd/actionlint@v1.7.7
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install requests_mock yamllint \
            types-requests types-PyYAML types-toml
          pip install -e .
      - name: Prepare field status files
        run: |
          for market in crypto forex stocks futures; do
            mkdir -p "results/$market"
            echo -e "field\tstatus\tvalue\nclose\tok\t1\nopen\tok\tabc" > "results/$market/field_status.tsv"
          done
      - name: Generate specs for all markets
        run: |
          for market in crypto forex stocks futures; do
            tvgen generate --market $market --output specs/openapi_${market}.yaml  # yamllint disable-line rule:line-length
          done
      - name: Validate all generated specs
        run: |
          for spec in specs/openapi_*.yaml; do
            yamllint "$spec"
            openapi-spec-validator "$spec"
          done
      - name: Fetch and rebase before PR
        run: |
          git fetch origin main
          git rebase origin/main
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          add-paths: 'specs/openapi_*.yaml'
          commit-message: 'chore: update generated specifications'
          title: 'Update OpenAPI specifications'
          body: 'Automated update of generated specifications.'
          branch: 'auto/spec-update'
        # - name: Notify on failure
        #   if: failure()
        #   uses: Ilshidur/action-slack@2.1.0
        #   with:
        #     webhook_url: ${{ secrets.SLACK_WEBHOOK }}
        #     msg: 'Workflow failed: ${{ github.workflow }} in ${{ github.repository }}'
