---
name: Update Specs
# yamllint disable rule:truthy

on:
  workflow_dispatch: {}  # yamllint disable-line rule:truthy
  schedule:
    - cron: '0 2 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Actionlint
        uses: rhysd/actionlint@v1.7.7
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install requests_mock yamllint
          pip install -e .
      - name: Generate spec
        run: tvgen generate --market crypto --output specs/openapi_crypto.yaml
      - name: Validate spec
        run: |
          yamllint specs/openapi_crypto.yaml
          openapi-spec-validator specs/openapi_crypto.yaml
      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          add: specs/openapi_crypto.yaml
          message: 'chore: update generated specifications'
          default_author: github_actions
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: 'chore: update generated specifications'
          title: 'Update OpenAPI specifications'
          body: 'Automated update of generated specifications.'
          branch: 'auto/spec-update'
