---
name: Update Specs
# yamllint disable rule:truthy

on:
  workflow_dispatch: {}  # yamllint disable-line rule:truthy
  schedule:
    - cron: '0 2 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12']
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Actionlint
        uses: rhysd/actionlint@v1.7.7
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install requests_mock yamllint
          pip install -e .
      - name: Generate specs for all markets
        run: |
          for market in crypto forex stocks futures; do
            tvgen generate --market $market --output specs/openapi_${market}.yaml
          done
      - name: Validate all generated specs
        run: |
          for spec in specs/openapi_*.yaml; do
            yamllint "$spec"
            openapi-spec-validator "$spec"
          done
      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          add: specs/openapi_*.yaml
          message: 'chore: update generated specifications'
          default_author: github_actions
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: 'chore: update generated specifications'
          title: 'Update OpenAPI specifications'
          body: 'Automated update of generated specifications.'
          branch: 'auto/spec-update'
      - name: Notify on failure
        if: failure()
        uses: Ilshidur/action-slack@v2.0.0
        with:
          webhook_url: ${{ secrets.SLACK_WEBHOOK }}
          msg: 'Workflow failed: ${{ github.workflow }} in ${{ github.repository }}'
