---
# yamllint disable rule:truthy rule:line-length
name: Update Specs

on:
  push:
    branches: [main]
  workflow_dispatch: {}
  schedule:
    - cron: '0 3 * * *'

permissions:
  contents: read
  pull-requests: read

jobs:
  generate:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.10', '3.11', '3.12']
    env:
      SERVER_URL: ${{ secrets.SERVER_URL }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'

      # Cache pip to speed up installs
      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ matrix.python-version }}-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: ${{ runner.os }}-pip-${{ matrix.python-version }}-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e ".[dev]"
          pip install yamllint safety pip-audit
          pip install openapi-spec-validator

      - name: Show versions
        run: |
          python --version
          pip --version
          tvgen --help

      - name: Fetch data and generate specs
        run: |
          set -euo pipefail
          tvgen fetch-data
          tvgen generate

      - name: Validate specs
        run: |
          tvgen validate

      - name: Security audit
        run: |
          safety check
          pip-audit
          pip check

      - name: Upload artifacts
        if: github.event_name == 'push'
        uses: actions/upload-artifact@v4
        with:
          name: specs-${{ matrix.python-version }}
          path: |
            specs/*.json
            results/
          if-no-files-found: error

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: 'chore: update generated specifications'
          title: 'Update OpenAPI specifications'
          body: 'Automated update of generated specifications.'
          branch: openapi-specs-${{ github.run_number }}
          token: ${{ secrets.GITHUB_TOKEN }}

  quality:
    needs: generate
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.10', '3.11', '3.12']
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e ".[dev]"
          pip install ruff black mypy pytest-cov

      - name: Ruff
        run: ruff check src/ tests/

      - name: Black
        run: black --check src/ tests/

      - name: MyPy
        # src/config.py contains runtime checks that confuse mypy.
        # It is excluded here to avoid failing the release pipeline.
        run: mypy src/tv_generator --exclude src/tv_generator/config.py

      - name: Pytest with coverage
        run: pytest --cov=src/tv_generator --cov-report=xml -q

      - name: Upload coverage to Codecov
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        if: ${{ env.CODECOV_TOKEN != '' }}
        run: |
          pip install codecov
          codecov -t "$CODECOV_TOKEN"
